sudo: required
language: python
python:
  - "3.7"
#services:
#  - docker
#before_script:
#  - docker-compose build
script:
  - python manage.py test
notifications:
  email: false
#cache:
#  pip: true
