site_name: dsbj
site_description: University Event Management App
repo_url: https://github.com/dsbjofficial/dsbj-backend
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/dsbjofficial">dsbjofficial</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
